## Numpy
- Statistical


In [1]:
%pip install numpy

     ---------------------------------------- 6.0/6.0 MB 2.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

## Shortcuts
- `ctl + alt` + enter -> run the cell 
- `shift + enter` -> next cell

In [11]:
marks = np.array([90, 80, 20, 40])
marks * 2 # actually multiplying element 

marks_list=[90, 80, 20, 40]
# marks_list * 2 # repeating array 
marks_list_double = [x * 2 for x in marks_list]

In [13]:
np.ones(200) # identity matrix
np.zeros(90)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [15]:
np.arange(10)
np.arange(1, 10)
np.arange(1, 10, 2) # begin, end, step

array([1, 3, 5, 7, 9])

In [16]:
np.arange(10) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [17]:
np.arange(10) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
first_ten_nums = np.arange(1, 11)
all_gt_five = first_ten_nums > 5
print(first_ten_nums[all_gt_five])
print(first_ten_nums[first_ten_nums > 5])
first_ten_nums

## Task
create a 1..200 numbers and provide a numpy array with all even numbers



In [ ]:
nums = np.arange(1, 201, 2) # with skip/step
nums

nums = np.arange(1, 201)
even_nums = nums[nums % 2 == 0] # without skip/step
even_nums

In [ ]:
ages = np.random.randint(18, 60, 50) # last val is for how much rand vals one wants
ages_list = ages.tolist()
ages_list

## Operations
- multiply
- division
- addition
- subtraction

In [55]:
np.arange(10) * 2
np.arange(10) + 2
np.arange(10) / 2
np.arange(10) - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

## Performance 
- arrange 

In [ ]:
%%time
double_ages = [age * 2 for age in ages_list]
print(double_ages)

In [31]:
%%time
dbl_ages = ages * 2
dbl_ages

CPU times: total: 0 ns
Wall time: 0 ns


array([114,  68,  38,  86,  54,  92,  42,  46,  42,  88,  92,  62, 116,
       104, 118,  52,  54,  56,  70,  36,  86,  88,  82,  38, 104,  84,
       108,  68, 112, 106, 110, 110, 114,  58,  90,  70,  36, 116,  38,
        56, 108,  74,  46, 112,  36,  46,  80,  94,  68, 106])

## Statistical oriented - mean, mode, median, std
- `mean` <-> average
- `mode` <-> the most repeated number (most popular)
- `median` <-> middle number when sorted, if list even then take the average of the two middle nums
- `standard deviation` <-> average distance between the mean and median


In [33]:
marks = np.random.randint(40, 100, 10)
print(marks)
print(marks.mean())
print(np.mean(marks))

[56 92 68 58 66 95 61 51 87 91]
72.5
72.5


In [34]:
np.median(marks)

67.0

In [35]:
np.sum(marks)

725

In [54]:
np.std(marks)

16.057708429287164

## Task 
investment = 1_000
rate_of_interest -> 5%
at the end of 2 years what is the balance?

year 1 R50 -> R1050
year 2 R52.5 -> R1102.5

### Task 1
at the every year tell me balance for 10 years

### Task 2 
at the year of ten years what will be the balance

### Task 3
How is much % its increase is compared to first year

In [48]:
# Task 1
years = np.arange(1, 11)
yearly_return = 1000 * 1.05 ** years
print(yearly_return)

[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]


In [50]:
# Task 2
balance_year_10 = yearly_return[-1] 
print(balance_year_10)

1628.894626777442


In [53]:
# Task 3
# balance_year_1 = yearly_return[0]  
investment = 1000
percentage_increase = ((balance_year_10 - investment) / investment) * 100

print(round(percentage_increase, 2))


62.89


## Useful methods
- string methods
- unique
- max, min

In [56]:
salaries = np.random.randint(1_000, 10_000, 10)
print(salaries)

[8713 1720 1284 3191 1251 9587 3324 3320 3086 9695]


In [61]:
print(np.max(salaries), np.argmax(salaries))
print(np.min(salaries), np.argmin(salaries))


9695 9
1251 4


In [58]:
nums = np.random.randint(1, 4, 10)
nums

array([3, 2, 3, 1, 2, 3, 2, 1, 3, 2])

In [60]:
uniq_names = np.unique(nums)
np.flip(uniq_names) # reverse the array

array([3, 2, 1])

In [70]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
unique_items = np.unique(np.char.lower(np.char.strip(items)))
print(unique_items)

['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


In [85]:
start_with_b = unique_items[np.char.startswith(unique_items, 'b')]
print(start_with_b)

contain_e_once = unique_items[np.char.count(unique_items, 'e') == 1]
print(contain_e_once)

['banana' 'blueberry']
['apple' 'cucumber' 'grape' 'lemon' 'orange' 'raspberry']


In [89]:
hourly_vistitors = [468, 279,  73, 272, 406, 128, 302, 216, 140, 82]
arr_hourly_vistitors = np.array(hourly_vistitors)
 
print("Total visitors:", np.sum(arr_hourly_vistitors))
print("Peak hour:", np.argmax(arr_hourly_vistitors)+1)
print(f"Average visitors per hour: {np.mean(arr_hourly_vistitors)}/h")

Total visitors: 2366
Peak hour: 1
Average visitors per hour: 236.6/h


In [91]:
nums_3D = np.array([[1, 3, 4],
                   [6, 10, 77],
                   [9, 20, 24]
                   ])
nums_3D.shape

(3, 3)

In [94]:
nums1 = np.arange(1, 10)
print(nums1)
nums1.shape 


[1 2 3 4 5 6 7 8 9]


(9,)

In [95]:
nums1.reshape(3,3).shape

(3, 3)

In [96]:
nums_3x3 = nums1.reshape(3,3) 
np.sum(nums_3x3)
np.mean(nums_3x3)
np.std(nums_3x3)

2.581988897471611

In [105]:
print(nums_3x3)
np.sum(nums_3x3, axis=0) # column
np.sum(nums_3x3, axis=1) # row
np.sum(np.sum(nums_3x3, axis=1)) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [107]:
nums_3x3 * 2
nums_3x3 + 2
nums_3x3 / 2
nums_3x3 - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [112]:
stats = np.random.randint(40, 100, 9)
stats

array([40, 57, 44, 53, 50, 92, 56, 81, 77])

In [115]:
stats_3x3 = stats.reshape(3, 3)
print(stats_3x3)
print(nums_3x3)

print("\nResults")
print(stats_3x3 + nums_3x3)

[[40 57 44]
 [53 50 92]
 [56 81 77]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Results
[[41 59 47]
 [57 55 98]
 [63 89 86]]


In [116]:
# task 1: find the average temperature of every part of the room 
# expected output 3x3 matrix with average of sensors
# [23.3 .....]
# [..........]
# [........25]

sensor1 = np.array([[23, 25, 22],
                    [20, 21, 20],
                    [26, 25, 24]])
 
sensor2 = np.array([[24, 23, 24],
                    [22, 22, 23],
                    [25, 26, 26]])


average_temperature = (sensor1 + sensor2) / 2
print("Average temperature of every part of the room:")
print(average_temperature)

Average temperature of every part of the room:
[[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]


In [125]:
# task 2: find the average temp given across a suite by sensor 1 and sensor 2 
avg_temp_per_suite_sensor1 = np.round(np.mean(sensor1, axis=1), 1)
avg_temp_per_suite_sensor2 = np.round(np.mean(sensor2, axis=1), 1)

print(avg_temp_per_suite_sensor1)
print(avg_temp_per_suite_sensor2)

[23.3 20.3 25. ]
[23.7 22.3 25.7]


In [128]:
# task 3: combine average temperature of sensor 1 and sensor 2 per suite
combined = (avg_temp_per_suite_sensor1 + avg_temp_per_suite_sensor2)/2
print(combined)

[23.5  21.3  25.35]
